name: Generate Snake ğŸ

on:
  schedule:
    - cron: "0 */6 * * *"  # Her 6 saatte bir Ã§alÄ±ÅŸtÄ±r
  workflow_dispatch:       # Manuel tetikleme

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v4

      - name: YÄ±lan SVG'sini oluÅŸtur
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: furkanduran60
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: SVG dosyasÄ±nÄ± 'output' branÅŸÄ±na gÃ¶nder
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
